---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# Log Periodic Power Low(LPPL)

<!-- badges: start -->
<!-- badges: end -->

The package implements Log-Periodic-Power-Low(LPPL) models proposed to test for financial bubbles.

## Installation

You can install the released version of lppl from [CRAN](https://CRAN.R-project.org) with:

``` r
install.packages("lppl")
```

And the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("mcgyver3/lppl")
```
## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(lppl)

tradedate <- lppl::NASDAQ$Date
price <- lppl::NASDAQ$Close

Result <- lppl.validates(tradedate =tradedate
                         ,price = price
                         ,mb=c(1:2)
                         ,MovingWindows=c(5)
                         ,gaRunCnt=100
                         ,gaGenerations=200
                         ,gaPopulation=50)
```


```{r cars}
class(Result)
```
